version: "3"

services:
  coordinator:
    image: trinodb/trino:463
    container_name: trino
    ports:
      - 8080:8080
    volumes:
      - ./trino:/etc/trino
    depends_on:
      - opa
      - jaeger
  opa:
    image: openpolicyagent/opa:0.69.0
    container_name: opa
    ports:
      - 8181:8181
    command:
      - run
      - --server
      - /policies
      - --log-level
      - debug
    volumes:
      - ./opa:/policies
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - 16686:16686
      - 4317:4317
    environment:
      - COLLECTOR_OTLP_ENABLED=true
